### ISSUE TITLE
Error displaying system logs

### ISSUE THREAD

**Issue by Dep1911** [kvazis/hassos#1]
In configuration:
```
panel_custom:
  - name: server_state
    sidebar_title: 'System'
    sidebar_icon: mdi:server
    js_url: /api/hassio/app/entrypoint.js
    url_path: 'hassio/system'
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

```
Previously, when selecting a log provider, the log changed. From some point, with any choice (Supervisor, Core, Host, etc.) the Supervisor log always shows.
Is this the case for everyone or is it just me?
